"""
Django models generated from JSON schema.
Generated by SchemaBloom (JSON-to-ORM)
"""

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
import uuid


class Users(models.Model):
    """
    Users model.
    """
    
    id = models.AutoField(primary_key=True)
    email = models.TextField()
    
    
    class Meta:
        db_table = 'users'
        verbose_name = 'Users'
        verbose_name_plural = 'Users'
    
    def __str__(self):
        return str(self.email)
    

 